---
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  notify: Restart apache
